[deploy_target]
deploy ansible_host=3.25.174.66 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/banking-key.pem

[monitoring]
splunk ansible_host=3.27.228.83 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/banking-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
